### ISSUE TITLE
ZETTELKASTEN_AUTO_GIT_PUSH problem

### ISSUE THREAD

**Issue by TheEditor** [AndrewCopeland/zettelkasten#12]
If ZETTELKASTEN_AUTO_GIT_PUSH="yes", but there is not actually a repo, doing a "zk new gitpushtest" dies in main() at "sync &>/dev/null".

Not being a linux guy I know just enough to sorta figure out what's going on, but not enough to really understand. I grok sync and /dev/null. Decades ago at school that was *dummy*.

But tough to find docs that tell me what "&" does and stops me there. An Echo shows me the args are passed in properly.

**Comment by AndrewCopeland** [comment]
This commit should resolve the issue: https://github.com/AndrewCopeland/zettelkasten/commit/127704e8b234391e0b9f0a344da6fd0a4c30eb0a

It will validate the `ZETTELKASTEN_DIR` is a git repo when `ZETTELKASTEN_AUTO_GIT_PUSH` is set to `yes`. It will error out that is it not a directory and will prompt you to change the `~/.zettelkasten` config file.

**Comment by TheEditor** [comment]
What was happening at sync &>/dev/null that caused a problem when gitpush is set incorrectly?

**Comment by AndrewCopeland** [comment]
it most likely failed when performing a `git pull` in the directory you specified. Since it is a not a git repo this command is failing. The reason why the application is failing is because on line 2 of the `zk` file I am setting `set -e` which means `-e  Exit immediately if a command exits with a non-zero status.`

Does this resolve the issue?

**Comment by TheEditor** [comment]
The fix does now cause an error message to pop during the zk new command.

I get how the git pull would fail. What I don't understand is the **where**. I put Echos in main() and it was definitely at the sync statement where it died.

**Comment by AndrewCopeland** [comment]
When `ZETTELKASTEN_AUTO_GIT_PUSH` is set to `yes` then it will pull from the git repo everytime you run `zk` because we want to make sure your local kasten is in sync with the cloud kasten. And it will push to the git repo whenever you update or create a new zettel. I think this is expected behaviour. If you wanna see more information without writing echo statements run the `zk` command using `bash -x` like `bash -x ./zk new test-zettel-1`.
 
`sync` is a function within the `zk` file. It can be found here: https://github.com/AndrewCopeland/zettelkasten/blob/master/zk#L405

Hopefully this answers your question.

**Comment by TheEditor** [comment]
Ok, that helps a bit. I had been looking at the man page for sync, not seeing you had redefined it.

Still, I don't quite get the "&>/dev/null". I get that you're sending the text sync() generates to /dev/null to keep things quiet. Just don't understand the "&" and what it represents.

**Comment by AndrewCopeland** [comment]
In this case it is redirecting stderr to `/etc/null` so it doesn't show the `git pull` output.
I know how to do it from this link: https://www.cyberciti.biz/faq/how-to-redirect-output-and-errors-to-devnull/

**Comment by AndrewCopeland** [comment]
I renamed the method from `sync` to `sync_zettelkasten` so someone else does not get confused. Also fixed a bug in validation of git repo which was failing even when the dir was actually a git repo.
In this commit:
https://github.com/AndrewCopeland/zettelkasten/commit/12f1a5abdf2175d448f3166c129971f63a4ac04a

**Comment by TheEditor** [comment]
Thanks much. Didn't help much, but no need for me to obsess over it. I get the general drift.
